### ISSUE TITLE
Detailed instructions?

### ISSUE THREAD

**Issue by sshchmod777** [ChristianSenning/eToroSBot#2]
Hello,

I'm just new to bash and having a challenge running the script on WIndows w/ ubuntu. Do you have more detailed step by step instructions? Thank you!

**Comment by ChristianSenning** [comment]
Hi
Yes there is now a detailed installation guide in the main folder:
https://github.com/ChristianSenning/eToroSBot/blob/master/Installation_guide.pdf
Hope that help to get the bot running.
Best regards,
Christian

**Comment by stathisgeo20** [comment]
Hi @ChristianSenning.
I followed the instructions listed above however I am having a few problems also to get it to work. I get the errors
./eToroSBot.bash line 46: uuid: command not found 
./eToroSBot.bash line 46: uuid: command not found 
./eToroSBot.bash line 251: tempfile: command not found
./eToroSBot.bash line 252: tempfile: command not found 
./eToroSBot.bash line 253: tempfile: command not found
./eToroSBot.bash line 256: : No such file or directory 
./eToroSBot.bash line 257: : No such file or directory
./eToroSBot.bash line 258: : No such file or directory

Thank you in advance
Stathis
