### ISSUE TITLE
Error after following instructions 

### ISSUE THREAD

**Issue by stathisgeo20** [ChristianSenning/eToroSBot#3]
Hi @ChristianSenning.
I followed the instructions listed above however I am having a few problems also to get it to work. I get the errors
./eToroSBot.bash line 46: uuid: command not found
./eToroSBot.bash line 46: uuid: command not found
./eToroSBot.bash line 251: tempfile: command not found
./eToroSBot.bash line 252: tempfile: command not found
./eToroSBot.bash line 253: tempfile: command not found
./eToroSBot.bash line 256: : No such file or directory
./eToroSBot.bash line 257: : No such file or directory
./eToroSBot.bash line 258: : No such file or directory
Thank you in advance
Stathis

**Comment by edoreld** [comment]
You are getting these errors because the script is trying to execute commands that are not present in your operating system (uuid and tempfile). 

Either run the script on a machine that has these commands (i.e: Ubuntu) or install the commands for your OS.

**Comment by stathisgeo20** [comment]
Hi @ChristianSenning 
Excellent. Thank you for your reply.

That sorted out the issues. 

I have another question. How can I find the cid of a trader that is not listed in the cid.txt already 

Thank you once again 
Stathis

**Comment by ChristianSenning** [comment]
Hi Stathis
With the new version of the bot, you don't have to find the cid yourself. The bot searches the cid and updates the cid.txt file himself.
The responsible function for this new behavior is: getCidfFileOrUpdate()
Best regards
Christian
